# Generated by Django 3.1 on 2020-08-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pib', models.CharField(max_length=250)),
                ('order_number', models.CharField(max_length=100)),
                ('date_order', models.DateTimeField(auto_now=True)),
                ('contact', models.CharField(max_length=35)),
                ('location', models.CharField(max_length=250)),
                ('kadastr_number', models.CharField(max_length=30)),
                ('ipn', models.CharField(max_length=50)),
                ('pasport', models.CharField(max_length=25)),
                ('rayon', models.CharField(choices=[('loz', 'Lozovaya'), ('kup', 'Kupyansk')], max_length=30)),
                ('sovet', models.CharField(max_length=150)),
                ('type_of_work', models.CharField(max_length=200)),
                ('zakaz', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
