# Generated by Django 3.1 on 2020-08-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0002_auto_20200817_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='zakaz',
        ),
        migrations.DeleteModel(
            name='Geodeziya',
        ),
        migrations.AddField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zemradnyk.orderer'),
        ),
    ]
