# Generated by Django 3.1 on 2020-08-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0005_auto_20200818_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='type_of_work',
            new_name='type_of_works',
        ),
    ]
