# Generated by Django 3.1 on 2020-09-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0006_auto_20200818_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Geodeziya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exist_mark', models.BooleanField()),
                ('date', models.DateField()),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='zemradnyk.order')),
            ],
        ),
    ]
