# Generated by Django 3.1 on 2020-09-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0007_auto_20200907_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geodeziya',
            old_name='order_number',
            new_name='order',
        ),
    ]
