# Generated by Django 3.1 on 2020-09-07 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0008_auto_20200907_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodeziya',
            name='developer',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
