# Generated by Django 3.1 on 2020-09-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0009_geodeziya_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodeziya',
            name='developer',
        ),
        migrations.AlterField(
            model_name='geodeziya',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_geodeziya', to='zemradnyk.order'),
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateField()),
                ('pre_response_date', models.DateField()),
                ('response_date', models.DateField()),
                ('first_session_date', models.DateField()),
                ('first_session_response_date', models.DateField()),
                ('response_rada', models.CharField(choices=[('yes', 'Позгодженно'), ('no', 'Відмово')], max_length=30)),
                ('oskargenya_1', models.CharField(max_length=40)),
                ('dev_message_mov_zgoda', models.CharField(max_length=40)),
                ('oskargenya_2', models.CharField(max_length=40)),
                ('sending_date_zatverg', models.DateField()),
                ('sending_response_date_zatverg', models.DateField()),
                ('oskargenya_zatverg', models.CharField(max_length=40)),
                ('register', models.CharField(max_length=40)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_low', to='zemradnyk.order')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidpovidalny', models.CharField(max_length=50)),
                ('first_date', models.DateField()),
                ('akt_vigotovleno_date', models.DateField()),
                ('akt_pidpisano_date', models.DateField()),
                ('granichniy_complete_date', models.DateField()),
                ('complite_date', models.DateField()),
                ('pogodjenya', models.CharField(max_length=50)),
                ('expertise', models.CharField(max_length=50)),
                ('podonya_date', models.DateField()),
                ('number_ZV', models.CharField(max_length=50)),
                ('register', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_developer', to='zemradnyk.order')),
            ],
        ),
    ]
