# Generated by Django 3.1.1 on 2020-09-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0012_auto_20200908_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
