# Generated by Django 3.1.1 on 2020-09-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0014_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='developer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='register_ZD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='register',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
