# Generated by Django 3.1.1 on 2020-09-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0015_auto_20200909_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exist_mark',
            field=models.CharField(blank=True, choices=[('✓', 'yes'), ('✕', 'no')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rayon',
            field=models.CharField(choices=[('Лозовской', 'loz'), ('Купянский', 'kup')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='response_rada',
            field=models.CharField(blank=True, choices=[('Позгодженно', 'yes'), ('Відмова', 'no')], max_length=30, null=True),
        ),
    ]
