# Generated by Django 3.1.1 on 2020-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0016_auto_20200909_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exist_mark',
            field=models.CharField(blank=True, choices=[('✓', '✓'), ('✕', '✕')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rayon',
            field=models.CharField(choices=[('Лозовской', 'Лозовской'), ('Купянский', 'Купянский')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='response_rada',
            field=models.CharField(blank=True, choices=[('Позгодженно', 'Позгодженно'), ('Відмова', 'Відмова')], max_length=30, null=True),
        ),
    ]
