# Generated by Django 3.1.1 on 2020-09-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0018_auto_20200909_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='akt_pidpisano_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='akt_vigotovleno_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='complite_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dev_message_mov_zgoda',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='developer',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='exist_mark',
            field=models.CharField(blank=True, choices=[('✓', '✓'), ('✕', '✕')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expertise',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_session_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_session_response_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='granichniy_complete_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_ZV',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='oskargenya_1',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='oskargenya_2',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='oskargenya_zatverg',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payed',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='podonya_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pogodjenya',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pre_response_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='register',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='register_ZD',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='response_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='response_rada',
            field=models.CharField(blank=True, choices=[('Позгодженно', 'Позгодженно'), ('Відмова', 'Відмова')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sending_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sending_date_zatverg',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sending_response_date_zatverg',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='vidpovidalny',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
