# Generated by Django 3.1.1 on 2020-09-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0022_auto_20200911_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_session_response_date_plus_30_days',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sending_response_date_zatverg_plus_14_days',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='kadastr_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='vidpovidalny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zemradnyk.vipovilny'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
