# Generated by Django 3.1.1 on 2020-09-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0024_auto_20200913_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zemradnyk.rayon'),
        ),
    ]
