# Generated by Django 3.1.1 on 2020-09-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0026_kadastr_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rozrobnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='response_rada',
            field=models.CharField(blank=True, choices=[('Дозвіл', 'Дозвіл'), ('Не розглянуто протягом 1 міс.', 'Не розглянуто протягом 1 міс.'), ('Відмова', 'Відмова')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zemradnyk.rozrobnik'),
        ),
    ]
