# Generated by Django 3.1.1 on 2020-09-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0028_auto_20200922_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date_geodeziya',
        ),
    ]
