# Generated by Django 3.1.1 on 2020-09-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0029_auto_20200922_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_geodeziya',
            new_name='date',
        ),
    ]
