# Generated by Django 3.1.1 on 2020-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0030_auto_20200922_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadastr_number',
            name='kadastr_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
