# Generated by Django 3.1.1 on 2020-10-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemradnyk', '0031_auto_20200922_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadastr_number',
            name='in_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kadastr_number',
            name='reserv',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='sovet',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
